-- MySQL Script generated by MySQL Workbench
-- Sun May 21 22:15:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpf` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(200) NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `cep` VARCHAR(11) NOT NULL,
  `plano` VARCHAR(15) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_cliente`, `cpf`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_login` (
  `senha` INT NOT NULL,
  `id_login` INT UNSIGNED NOT NULL,
  `cpf` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_login`, `cpf`),
  CONSTRAINT `fk_tb_login_tb_cliente`
    FOREIGN KEY (`id_login` , `cpf`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente` , `cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
